schema: workflow/2022.04
name: learning_github_with_pipedream
settings:
  error_notification: true
triggers:
- id: hi_71HxRjE
steps:
- namespace: node
  runtime: nodejs18.x
  uses: "./node/entry.js"

